# Generated by Django 5.1.6 on 2025-02-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
